### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by Razikus** [spotify/helios#1180]
Hello, I can't find documentation for API requests. 
Is there anything like this?

**Comment by davidxia** [comment]
Sorry, there's currently no API docs. Most interaction with the helios master's API happens via the helios CLI tool or `HeliosClient` java class instead of via self-constructed HTTP requests. So we haven't seen a big need for API docs. The [code for API endpoints](https://github.com/spotify/helios/tree/master/helios-services/src/main/java/com/spotify/helios/master/resources) is rather self-documenting.

That being said, feel free to contribute some brief API docs if you feel inclined.
