### ISSUE TITLE
After undeploy, job keeps running for a few minutes

### ISSUE THREAD

**Issue by elifarley** [spotify/helios#933]
$> alias helios='helios -z http://localhost:5801'
$> helios create testjob:1 ubuntu:12.04 -- /bin/sh -c 'while true; do date; sleep 60; done'
$> helios deploy testjob:1 localhost
$> helios history testjob:1

localhost    2016-05-27 11:28:47.651    PULLING_IMAGE    NO           <none>                                                              
localhost    2016-05-27 11:29:04.336    CREATING         NO           <none>                                                              
localhost    2016-05-27 11:29:04.516    STARTING         NO           c764d9303c8d355c26fb6c5029a19749d339775b93de82628f28d85e7f225427    
localhost    2016-05-27 11:29:05.161    RUNNING          NO           c764d9303c8d355c26fb6c5029a19749d339775b93de82628f28d85e7f225427    

$> helios undeploy testjob:1 localhost
Undeploying testjob:1:4f7125bff35d3cecaac237da3ab17efca8a765f9 from [localhost]
localhost: done
$> helios history testjob:1 | grep STOPPED
<nothing shown>
$> helios history testjob:1 | grep STOPPING
<nothing shown>

If I wait for about 4 minutes, then I get:

$> helios history testjob:1 | grep STOPPED
localhost    2016-05-27 11:43:20.309    STOPPED          NO           25a642d9e6f2203743bd326f2309ff3f7bdc04f3fd850e60a75aa1afa4339769 

Perhaps the job state should immediately change to STOPPING after issuing the undeploy command.

**Comment by mattnworb** [comment]
This is as expected, because a container running a while/sleep loop like `'while true; do date; sleep 60; done'` doesn't respond to [the `SIGTERM` that `docker stop` sends](https://docs.docker.com/engine/reference/commandline/stop/) (which is what helios sends via the Docker Remote API when you undeploy a job). Helios tells Docker to wait 120 seconds after sending the SIGTERM to kill an unresponsive container with SIGKILL.

If you have a more well-behaved container that exits immediately, then the job exits immediately and the history reflects that:

```
$ ./helios-solo create nginx:2 nginx:1.9.0
...
$ ./helios-solo deploy nginx:2 solo.local
...
$ ./helios-solo undeploy nginx:2 solo.local; sleep 2; ./helios-solo history nginx:2
Undeploying nginx:2:a3f56da08826edc44068e3a6f88cd7af23003ba4 from [solo.local]
solo.local.: done
HOST           TIMESTAMP                  STATE            THROTTLED    CONTAINERID
solo.local.    2016-05-31 16:51:09.821    PULLING_IMAGE    NO           <none>
solo.local.    2016-05-31 16:51:11.039    CREATING         NO           <none>
solo.local.    2016-05-31 16:51:11.191    STARTING         NO           c176ce1e2cbdd52c275a04890da5fb6c9f6dd7d13caecf02a30b0b09dced3029
solo.local.    2016-05-31 16:51:11.468    RUNNING          NO           c176ce1e2cbdd52c275a04890da5fb6c9f6dd7d13caecf02a30b0b09dced3029
solo.local.    2016-05-31 16:51:52.879    STOPPED          NO           c176ce1e2cbdd52c275a04890da5fb6c9f6dd7d13caecf02a30b0b09dced3029
```

One unexpected thing I found while looking at this is that [the `STOPPING` state is only stored in the history when the job has a gracePeriod configured](https://github.com/spotify/helios/blob/66b6e8ddc197ee5484d8b79bc9c408bd4d91e3fa/helios-services/src/main/java/com/spotify/helios/agent/Supervisor.java#L349-L353). I think it would make more sense to write the `STOPPING` state unconditionally before telling docker to stop the container, since the stop itself might not be instantaneous. I'll create a new issue for this.
